# 数据源配置
spring:
    datasource:
#        url: jdbc:mysql://192.168.1.101:13306/chat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        url: jdbc:postgresql://192.168.1.101:15432/chat
        username: chat
        password: Bt8eNnbYeNJhDreB
        driver-class-name: org.postgresql.Driver

mybatis-plus:
    mapper-locations: classpath*:mappers/**/*.xml # 配置mapper文件位置


lxxx: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJseHh4IiwibG9naW5fdXNlcl9rZXkiOiI5ZTQyNDk3OC0zMWYwLTRkMzItYTA4NS1lZTE3MTQ0MzJjMjMifQ.EYbcpluJYTIXj5QeSwZ0tvm5t4I1Z8Gp5O-dVvuzUAUGHQjxNKPAe_CTb8i8Pyhu6Esf8f17rDLcq0pbDwr0Yw

zorroe: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ6b3Jyb2UiLCJsb2dpbl91c2VyX2tleSI6IjA1MjA1ZTUwLTJjNjYtNGYzMC1hZmU2LThkYjBhYzkzNWEwYSJ9.KdQ1-capyiOlcdEgi1jgVE68ISbpAdPCGljYQE0Kc54MyN3uHPAH-wlLxc3cqYknObdcHyJ5VbrGRHxz-qURng
