# 数据源配置
spring:
    datasource:
#        url: jdbc:mysql://192.168.1.101:13306/chat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        url: jdbc:postgresql://192.168.1.101:15432/chat
        username: chat
        password: Bt8eNnbYeNJhDreB
        driver-class-name: org.postgresql.Driver

mybatis-plus:
    mapper-locations: classpath*:mappers/**/*.xml # 配置mapper文件位置


lxxx: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJseHh4IiwibG9naW5fdXNlcl9rZXkiOiJiNGFhYTZmMS0yOTQ4LTQ0ZjAtYTliYy1iMjJmODU4ZmI5MjMifQ._PkeLztirfjcV7EnyyTKFEOnuyJ_NLYEQ6hqMMduj34O7ewcVehs1OkYC6SRF0kyULIlM0svc5il6v-PB0LqeQ

zorroe: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ6b3Jyb2UiLCJsb2dpbl91c2VyX2tleSI6ImU3M2E0ZTlkLThlZWMtNDI4Zi1hMGY4LWQ0NDhkYTQ0MGMzNCJ9.sm-zmY9skN85m9dUI2nFHwsPzvuhCmnFEwUOorXejuvbdQsu9AMnYj7LHMNslNBSy_asfNaKIv0iY9zfD87brA
